name: build

on:
  - push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: build
        run: |
          npm i -g yarn
          yarn && yarn build && yarn pkg
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: abird
          path: ./abird
