name: docker publish

on:
  - push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./abird
          push: true
          tags: anillc/abird:latest
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: ./abird-dn42-roa
          push: true
          tags: anillc/abird-dn42-roa:latest
